### ISSUE TITLE
App runs with debug but wont build with realease

### ISSUE THREAD

**Issue by fixer112** [kmcgill88/admob_flutter#12] opened 2019-01-05 09:46 UTC
I have the following error when i run flutter run --realease or flutter build apk command
C:\Users\ABUDHABI\Documents\flutter_project\wordcomb>flutter run --release
Initializing gradle...                                       5.2s
Resolving dependencies...                                   21.9s
Launching lib/main.dart on SM G960U in release mode...
Gradle task 'assembleRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :admob_flutter.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 21s
Gradle task 'assembleRelease'... Done                       83.2s
Gradle task assembleRelease failed with exit code 1

**Comment by fixer112** [comment] 2019-01-05 09:47
What can be the issue? please any help to fix this

**Comment by fixer112** [comment] 2019-01-05 11:19
android/build.gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter{ url "http://jcenter.bintray.com/"}
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    configurations.all() {
    resolutionStrategy.force "com.google.firebase:firebase-core:16.0.5"
    }
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

app/build.gradle

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
//apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
        //checkReleaseBuilds false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.altechtic.wordcomb"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        //multiDexEnabled true
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {

        release {

            signingConfig signingConfigs.release

            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }
    }
}

flutter {
    source '../..'
}


dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by fixer112** [comment] 2019-01-05 11:49
fixed, now release built with classpath 'com.android.tools.build:gradle:3.1.2' in gradle.build, but app crashes in release but runs on debug, any idea?

**Comment by fixer112** [comment] 2019-01-05 12:51
all fixed removing minifyEnabled true fixed it , but app wont be minified, why is minifying not working?

**Comment by YoussefKababe** [comment] 2019-01-05 12:59
Hi there! Thanks for your reports! I will be looking into this later today since many people have reported the same issue.  Will keep you updated!

**Comment by thaerhamza** [comment] 2019-04-11 20:57
> Hi there! Thanks for your reports! I will be looking into this later today since many people have reported the same issue. Will keep you updated!

please if exist fix this issue I will be waiting

**Comment by kmcgill88** [comment] 2019-05-23 01:08
#23 is a duplicate of this. Closing #23 .

**Comment by EliasDeuss** [comment] 2019-12-19 11:09
@YoussefKababe @kmcgill88 Has this issue been fixed?

**Comment by kmcgill88** [comment] 2020-09-22 13:57
stale, closing.

**Closed by kmcgill88** 2020-09-22 13:57 UTC
Labels: bug
