### ISSUE TITLE
Banner is re-created/re-loaded with each Navigator push()/pop() 

### ISSUE THREAD

**Issue by kestasb** [kmcgill88/admob_flutter#18] opened 2019-02-16 22:41 UTC
Banner is reloaded with each Navigator push()/pop(), both onBannerCreated and AdmobAdEvent.loaded are called even the banner is a child of a const StalessWidget, whose build() method isn't called.
Admob guidelines does not recommend to refresh banner manually.
Is it possible to avoid this behaviour?

**Comment by TheAlexandru** [comment] 2019-04-18 07:42
Have you found any solutions to that ? I have the same problem. 
Also most of the time I don't see any ads at all...

**Comment by mmahkamov** [comment] 2019-05-30 17:36
I was having a similar issue when the AdmobBanner widget was used in a ListView.

I wrapped AdmobBanner into a custom AdmobBannerWrapper stateful widget with AutomaticKeepAliveClientMixin - the issue was resolved.

**Comment by mmahkamov** [comment] 2019-05-30 17:39
I think the AdmobBanner widget should be implemented with AutomaticKeepAliveClientMixin out of the box because redundant reloading of banners should be avoided (because it generates false impressions?). We could optionally pass the value for the wantKeepAlive property in the constructor.

**Comment by sumitgohil** [comment] 2019-06-26 16:55
@mmahkamov  Can you help me out? How should be this Implemented? How did you resolve the issue?

**Comment by mmahkamov** [comment] 2019-06-27 10:29
> @mmahkamov Can you help me out? How should be this Implemented? How did you resolve the issue?

I've just wrapped AdmobBanner inside a stateful widget which implements AutomaticKeepAliveClientMixin:

```
class AdmobBannerWrapper extends StatefulWidget {
  final String adUnitId;
  final AdmobBannerSize adSize;

  AdmobBannerWrapper({
    Key key,
    this.adUnitId, this.adSize
  }) : super(key: key);

  @override
  AdmobBannerWrapperState createState() => AdmobBannerWrapperState();
}

class AdmobBannerWrapperState extends State<AdmobBannerWrapper> with AutomaticKeepAliveClientMixin {
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return AdmobBanner(
            adUnitId: widget.adUnitId, 
            adSize: widget.adSize
    );
  }
}

```

**Comment by sumitgohil** [comment] 2019-06-27 11:42
@mmahkamov  Looks like this doesn't work for me. The Banner ad still keeps reloading while popping view.

**Comment by CosmoInSpace** [comment] 2019-06-27 11:53
@mmahkamov I tried your method above, it seems the reloading doesn't stop although a new error appeared:
```
<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
```
(using the test banner ad)

also, I called the widget like so:
```
AdmobBannerWrapper(
                  adUnitId: 'ca-app-pub-3940256099942544/2934735716',
                  adSize: AdmobBannerSize.BANNER,
                ),
```

**Comment by mmahkamov** [comment] 2019-06-28 08:54
> @mmahkamov Looks like this doesn't work for me. The Banner ad still keeps reloading while popping view.

Are you using FutureBuilder by any chance?

**Comment by narayanansampath** [comment] 2019-09-27 16:37
> > @mmahkamov Can you help me out? How should be this Implemented? How did you resolve the issue?
> 
> I've just wrapped AdmobBanner inside a stateful widget which implements AutomaticKeepAliveClientMixin:
> 
> ```
> class AdmobBannerWrapper extends StatefulWidget {
>   final String adUnitId;
>   final AdmobBannerSize adSize;
> 
>   AdmobBannerWrapper({
>     Key key,
>     this.adUnitId, this.adSize
>   }) : super(key: key);
> 
>   @override
>   AdmobBannerWrapperState createState() => AdmobBannerWrapperState();
> }
> 
> class AdmobBannerWrapperState extends State<AdmobBannerWrapper> with AutomaticKeepAliveClientMixin {
>   bool get wantKeepAlive => true;
> 
>   @override
>   Widget build(BuildContext context) {
>     return AdmobBanner(
>             adUnitId: widget.adUnitId, 
>             adSize: widget.adSize
>     );
>   }
> }
> ```

This fix didn't work for me and I'm not using FutureBuilder too. Please help :(

**Comment by nimish1995** [comment] 2019-09-29 10:29
no working! Any solution? in every refresh of the list it shows blank blink which not looks good. and is there any way to preload the banner and show only if it's loaded??

**Comment by mmahkamov** [comment] 2019-09-29 10:37
The blink is happening because the background color of the native widget is white by default. You need to patch the native side to make the host view transparent.

**Comment by nimish1995** [comment] 2019-09-29 10:39
Can you share the code? How can do that?

**Comment by nimish1995** [comment] 2019-09-29 10:39
> 
> 
> The blink is happening because the background color of the native widget is white by default. You need to patch the native side to make the host view transparent.

Can you share the code? How can do that?

**Comment by narayanansampath** [comment] 2019-09-29 11:09
> The blink is happening because the background color of the native widget is white by default. You need to patch the native side to make the host view transparent.

I changed the container color to white as my screen background is white but the ad container still displays black color.

**Comment by nimish1995** [comment] 2019-09-29 11:27
> 
> 
> > The blink is happening because the background color of the native widget is white by default. You need to patch the native side to make the host view transparent.
> 
> I changed the container color to white as my screen background is white but the ad container still displays black color.

same here

**Comment by mmahkamov** [comment] 2019-10-01 11:52
> > The blink is happening because the background color of the native widget is white by default. You need to patch the native side to make the host view transparent.
> 
> Can you share the code? How can do that?

You can get the idea from the following patch or just ```git apply``` it.

```
From 7a8e1be7ae027626fc77db41386595268707119f Mon Sep 17 00:00:00 2001
From: Muzaffar Mahkamov <muzaffar@mahkamov.com>
Date: Sun, 30 Jun 2019 12:01:49 +0500
Subject: [PATCH] * making AdmobBanner background transparent

---
 .../com/shatsy/admobflutter/AdmobBanner.kt    |  1 +
 .../shatsy/admobflutter/TransparentView.kt    | 25 +++++++++++++++++++
 2 files changed, 26 insertions(+)
 create mode 100644 android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt

diff --git a/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt b/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
index 7319607..8077f89 100644
--- a/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
+++ b/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
@@ -44,6 +44,7 @@ class AdmobBanner(context: Context, messenger: BinaryMessenger, id: Int, args: H
   }
 
   override fun getView(): View {
+    adView.makeWindowTransparent()
     return adView
   }
 
diff --git a/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt b/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
new file mode 100644
index 0000000..0842c10
--- /dev/null
+++ b/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
@@ -0,0 +1,25 @@
+package com.shatsy.admobflutter
+
+import android.view.View
+import android.view.Window
+import android.graphics.Color
+import android.graphics.drawable.ColorDrawable
+
+public fun View.makeWindowTransparent() {
+  this.post {
+    try {
+      var parent = this.parent ?: return@post
+      while (parent?.parent != null) {
+        parent = parent.parent
+      }
+      val decorView = parent.javaClass.getDeclaredMethod("getView").invoke(parent)
+      val windowField = decorView.javaClass.getDeclaredField("mWindow")
+      windowField.isAccessible = true
+      val window = windowField.get(decorView) as Window
+      windowField.isAccessible = false
+      window.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
+    } catch (e: Exception) {
+      // log it
+    }
+  }
+}
\ No newline at end of file
-- 
2.20.1

```

**Comment by narayanansampath** [comment] 2019-10-01 14:41
> > > The blink is happening because the background color of the native widget is white by default. You need to patch the native side to make the host view transparent.
> > 
> > 
> > Can you share the code? How can do that?
> 
> You can get the idea from the following patch or just `git apply` it.
> 
> ```
> From 7a8e1be7ae027626fc77db41386595268707119f Mon Sep 17 00:00:00 2001
> From: Muzaffar Mahkamov <muzaffar@mahkamov.com>
> Date: Sun, 30 Jun 2019 12:01:49 +0500
> Subject: [PATCH] * making AdmobBanner background transparent
> 
> ---
>  .../com/shatsy/admobflutter/AdmobBanner.kt    |  1 +
>  .../shatsy/admobflutter/TransparentView.kt    | 25 +++++++++++++++++++
>  2 files changed, 26 insertions(+)
>  create mode 100644 android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
> 
> diff --git a/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt b/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
> index 7319607..8077f89 100644
> --- a/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
> +++ b/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
> @@ -44,6 +44,7 @@ class AdmobBanner(context: Context, messenger: BinaryMessenger, id: Int, args: H
>    }
>  
>    override fun getView(): View {
> +    adView.makeWindowTransparent()
>      return adView
>    }
>  
> diff --git a/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt b/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
> new file mode 100644
> index 0000000..0842c10
> --- /dev/null
> +++ b/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
> @@ -0,0 +1,25 @@
> +package com.shatsy.admobflutter
> +
> +import android.view.View
> +import android.view.Window
> +import android.graphics.Color
> +import android.graphics.drawable.ColorDrawable
> +
> +public fun View.makeWindowTransparent() {
> +  this.post {
> +    try {
> +      var parent = this.parent ?: return@post
> +      while (parent?.parent != null) {
> +        parent = parent.parent
> +      }
> +      val decorView = parent.javaClass.getDeclaredMethod("getView").invoke(parent)
> +      val windowField = decorView.javaClass.getDeclaredField("mWindow")
> +      windowField.isAccessible = true
> +      val window = windowField.get(decorView) as Window
> +      windowField.isAccessible = false
> +      window.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
> +    } catch (e: Exception) {
> +      // log it
> +    }
> +  }
> +}
> \ No newline at end of file
> -- 
> 2.20.1
> ```

Can you please elaborate on the steps for applying this as patch. Thanks.

**Comment by nemoryoliver** [comment] 2019-10-19 02:25
> > > > The blink is happening because the background color of the native widget is white by default. You need to patch the native side to make the host view transparent.
> > > 
> > > 
> > > Can you share the code? How can do that?
> > 
> > 
> > You can get the idea from the following patch or just `git apply` it.
> > ```
> > From 7a8e1be7ae027626fc77db41386595268707119f Mon Sep 17 00:00:00 2001
> > From: Muzaffar Mahkamov <muzaffar@mahkamov.com>
> > Date: Sun, 30 Jun 2019 12:01:49 +0500
> > Subject: [PATCH] * making AdmobBanner background transparent
> > 
> > ---
> >  .../com/shatsy/admobflutter/AdmobBanner.kt    |  1 +
> >  .../shatsy/admobflutter/TransparentView.kt    | 25 +++++++++++++++++++
> >  2 files changed, 26 insertions(+)
> >  create mode 100644 android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
> > 
> > diff --git a/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt b/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
> > index 7319607..8077f89 100644
> > --- a/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
> > +++ b/android/src/main/kotlin/com/shatsy/admobflutter/AdmobBanner.kt
> > @@ -44,6 +44,7 @@ class AdmobBanner(context: Context, messenger: BinaryMessenger, id: Int, args: H
> >    }
> >  
> >    override fun getView(): View {
> > +    adView.makeWindowTransparent()
> >      return adView
> >    }
> >  
> > diff --git a/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt b/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
> > new file mode 100644
> > index 0000000..0842c10
> > --- /dev/null
> > +++ b/android/src/main/kotlin/com/shatsy/admobflutter/TransparentView.kt
> > @@ -0,0 +1,25 @@
> > +package com.shatsy.admobflutter
> > +
> > +import android.view.View
> > +import android.view.Window
> > +import android.graphics.Color
> > +import android.graphics.drawable.ColorDrawable
> > +
> > +public fun View.makeWindowTransparent() {
> > +  this.post {
> > +    try {
> > +      var parent = this.parent ?: return@post
> > +      while (parent?.parent != null) {
> > +        parent = parent.parent
> > +      }
> > +      val decorView = parent.javaClass.getDeclaredMethod("getView").invoke(parent)
> > +      val windowField = decorView.javaClass.getDeclaredField("mWindow")
> > +      windowField.isAccessible = true
> > +      val window = windowField.get(decorView) as Window
> > +      windowField.isAccessible = false
> > +      window.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
> > +    } catch (e: Exception) {
> > +      // log it
> > +    }
> > +  }
> > +}
> > \ No newline at end of file
> > -- 
> > 2.20.1
> > ```
> 
> Can you please elaborate on the steps for applying this as patch. Thanks.

I second this. please help us bro... thanks a lot

**Comment by kmcgill88** [comment] 2019-10-19 04:26
Has anyone in this thread considered doing something like this? https://github.com/kmcgill88/admob_flutter/issues/61#issuecomment-520670535

**Comment by nemoryoliver** [comment] 2019-11-01 22:42
> #61 (comment)

That is a nice workaround. But I'd rather use firebase_admob for that.

**Comment by EliasDeuss** [comment] 2019-12-19 11:16
@kestasb Where you able to get a work around for this issue?

**Comment by trqalothman** [comment] 2020-01-30 13:17
Any update/fix for this issue? it is one thing that is holding me back from the new release :(

**Closed** 2020-02-10 20:46 UTC
Labels: enhancement, help wanted, more info required

**Comment by benevolent13** [comment] 2020-02-24 10:25
> I was having a similar issue when the AdmobBanner widget was used in a ListView.
> 
> I wrapped AdmobBanner into a custom AdmobBannerWrapper stateful widget with AutomaticKeepAliveClientMixin - the issue was resolved.

Doesn't work for me.It gets reloaded everytime setState is called. :(

**Comment by erperejildo** [comment] 2020-02-26 15:48
> class AdmobBannerWrapper extends StatefulWidget {
>   final String adUnitId;
>   final AdmobBannerSize adSize;
> 
>   AdmobBannerWrapper({
>     Key key,
>     this.adUnitId, this.adSize
>   }) : super(key: key);
> 
>   @override
>   AdmobBannerWrapperState createState() => AdmobBannerWrapperState();
> }
> 
> class AdmobBannerWrapperState extends State<AdmobBannerWrapper> with AutomaticKeepAliveClientMixin {
>   bool get wantKeepAlive => true;
> 
>   @override
>   Widget build(BuildContext context) {
>     return AdmobBanner(
>             adUnitId: widget.adUnitId, 
>             adSize: widget.adSize
>     );
>   }
> }

this didn't work for me

**Comment by erperejildo** [comment] 2020-02-26 15:52
This quite important error has more than a year now

**Comment by sumitgohil** [comment] 2020-02-26 17:01
I'm not sure if I've solved the problem or not in some niche manner. But it has kinda worked for me. Also, I don't remember the changed I mad. I changed channel name too inside the package so PR won't be a good idea. I can create a git repo with my lib and someone can check if that works.

**Comment by sumitgohil** [comment] 2020-02-26 17:07
I am not sure if I've made a solution to this, but it kinda worked for me. I made changed to this long back and I don't really have a track on them. I've also changed channel names and it's done to fork of a previous version of this lib. It might not contain features available in the newer version. I've added this to my repo. If someone could check and see if this works. 

https://github.com/sumitgohil/flutter_admob_plugin

**Comment by EliasDeuss** [comment] 2020-02-27 02:37
@sumitgohil @erperejildo It is in the package but hasn't been updated in the pub.dev 

Use this for now:

```
admob_flutter:
    git:
      url: git://github.com/kmcgill88/admob_flutter.git
```

**Comment by erperejildo** [comment] 2020-02-27 11:44
> @sumitgohil @erperejildo It is in the package but hasn't been updated in the pub.dev
> 
> Use this for now:
> 
> ```
> admob_flutter:
>     git:
>       url: git://github.com/kmcgill88/admob_flutter.git
> ```

I can confirm this, it works.

Let's see when this gets merged

**Comment by kinton** [comment] 2021-01-10 20:35
Still aving the problem with TabBar and AutomaticKeepAliveClientMixin
